project:
  type: website

website:
  title: "Singapore Trade Partners Analysis"
  navbar:
    right:
      - text: "Proposal"
        href: Proposal.qmd
format:
  html:
    theme: cosmo
    toc: true
